# Generated by Django 5.0.1 on 2025-11-16 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisRun',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('run_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('total_roles_analyzed', models.IntegerField(default=0)),
                ('total_employees_analyzed', models.IntegerField(default=0)),
                ('departments_analyzed', models.JSONField(default=list)),
                ('execution_time_seconds', models.FloatField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('org_structure_gaps', models.TextField(blank=True, null=True)),
                ('responsibility_gaps', models.TextField(blank=True, null=True)),
                ('workload_gaps', models.TextField(blank=True, null=True)),
                ('skills_gaps', models.TextField(blank=True, null=True)),
                ('recommendations', models.JSONField(default=list)),
            ],
            options={
                'verbose_name': 'Analysis Run',
                'verbose_name_plural': 'Analysis Runs',
                'db_table': 'analysis_runs',
                'ordering': ['-run_date'],
            },
        ),
        migrations.CreateModel(
            name='JobRole',
            fields=[
                ('role_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('role_title', models.CharField(max_length=200)),
                ('department', models.CharField(max_length=100)),
                ('level', models.CharField(choices=[('entry', 'Entry Level'), ('junior', 'Junior'), ('mid', 'Mid Level'), ('senior', 'Senior'), ('lead', 'Lead'), ('manager', 'Manager'), ('director', 'Director'), ('vp', 'Vice President'), ('c_level', 'C-Level Executive')], max_length=20)),
                ('responsibilities', models.JSONField(default=list, help_text='List of responsibilities')),
                ('required_skills', models.JSONField(default=list, help_text='List of required skills')),
                ('reports_to', models.CharField(blank=True, max_length=50, null=True)),
                ('current_headcount', models.IntegerField(default=0)),
                ('team_size', models.IntegerField(default=0, help_text='Number of direct reports')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Job Role',
                'verbose_name_plural': 'Job Roles',
                'db_table': 'job_roles',
                'ordering': ['department', 'level', 'role_title'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('department', models.CharField(max_length=100)),
                ('hire_date', models.DateField()),
                ('workload_status', models.CharField(choices=[('underutilized', 'Underutilized'), ('normal', 'Normal'), ('overloaded', 'Overloaded')], default='normal', max_length=20)),
                ('skills', models.JSONField(default=list, help_text='List of employee skills')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='roles_analyzer.jobrole')),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
                'db_table': 'employees',
                'ordering': ['department', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MissingRole',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('recommended_role_title', models.CharField(max_length=200)),
                ('department', models.CharField(max_length=100)),
                ('level', models.CharField(max_length=20)),
                ('gap_type', models.CharField(help_text='Type of gap: structural, skills, workload, etc.', max_length=100)),
                ('justification', models.TextField(help_text='Why this role is needed')),
                ('expected_impact', models.TextField(help_text='Expected business impact')),
                ('priority', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=20)),
                ('recommended_headcount', models.IntegerField(default=1)),
                ('estimated_timeline', models.CharField(help_text='e.g., Immediate, 3 months, 6 months', max_length=100)),
                ('required_skills', models.JSONField(default=list)),
                ('responsibilities', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('analysis_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='missing_roles', to='roles_analyzer.analysisrun')),
            ],
            options={
                'verbose_name': 'Missing Role Recommendation',
                'verbose_name_plural': 'Missing Role Recommendations',
                'db_table': 'missing_roles',
                'ordering': ['-analysis_run__run_date', 'priority', 'recommended_role_title'],
            },
        ),
    ]
